include:
  - board: corneish_zen_v2_left
    # snippet: zmk-usb-logging  # uncomment to enable logging
  - board: corneish_zen_v2_right
    # snippet: zmk-usb-logging  # uncomment to enable logging
  - board: seeeduino_xiao_ble
    shield: corneish_zen_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corneish_zen_dongle_with_studio
  - board: nice_nano_v2
    shield: settings_reset
