include:
  - board: corneish_zen_left//zmk
    artifact-name: corneish_zen_left
    # snippet: zmk-usb-logging  # uncomment to enable logging
  - board: corneish_zen_right//zmk
    artifact-name: corneish_zen_right
    # snippet: zmk-usb-logging  # uncomment to enable logging
  - board: xiao_ble//zmk
    shield: corneish_zen_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corneish_zen_dongle
  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: settings_reset
